include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    deprecated_member_use: false
    use_build_context_synchronously: false

analyzer:
  errors:
    deprecated_member_use: ignore
    avoid_print: ignore
    use_build_context_synchronously: ignore
