// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsoya_crCm58Herb6Cn6-8D81q1S1cSJg',
    appId: '1:641122196636:web:d2a7f39b5d4c0b35dae159',
    messagingSenderId: '641122196636',
    projectId: 'disaster-response-bd',
    authDomain: 'disaster-response-bd.firebaseapp.com',
    storageBucket: 'disaster-response-bd.firebasestorage.app',
    measurementId: 'G-JJB928K4FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANKznuS3Un0Dk3IVhVfcdyhZUBsdzzHUQ',
    appId: '1:641122196636:android:7e670a2e55b84aabdae159',
    messagingSenderId: '641122196636',
    projectId: 'disaster-response-bd',
    storageBucket: 'disaster-response-bd.firebasestorage.app',
  );
}
